num_rounds: 200
num_clients_per_round: 60
learning_rate: 0.01
epochs_per_round: null
batches_per_round: 32
same_train_test_clients: True

selector: random
num_inclusive_exclusive_clients: 20

results_dir_path: "./results/table2_leaf_paper_partial_FeMNIST"
